### ISSUE TITLE
can blacklight_unapi work with rails4?

### ISSUE THREAD

**Issue by es287** [cbeer/blacklight_unapi#2]
gemspec seems to require rails3

**Comment by cbeer** [comment]
I've updated the gem (958c651ef6631d0cad8e5f4add6e4516d7fee687) to use Blacklight 5.x and any version of Rails. 

There are some configuration changes you'll want to make. In your catalog_controller, you'll want something like:

```ruby
    config.unapi = {
      'oai_dc_xml' => { :content_type => 'text/xml' } 
    }
    config.index.partials << 'microformat'
    config.show.partials << 'microformat'
```

**Comment by es287** [comment]
thanks Chris!
